### ISSUE TITLE
UNSUPPORTED: Could you share fix for y2028 for original cdrtools?

### ISSUE THREAD

**Issue by Giulio-xyz** [samboy/iso9660#2]
Could you share somewhere the patch for the original cdrtools:
https://news.ycombinator.com/item?id=28827388
         " However, even though I gave him a fix, he was unable to apply it, probably because of his poor health."
I tried copying and pasting the content of iso9660_date from this github into cdrtoools/mkisofs/mkisofs.c but Windows will still show no date/time for files in the ISO with dates after 2028.
I'd like to be sure this is all is needed before verifying I did everything correctly (patching, building, testing, ...).

Thanks.

**Comment by samboy** [comment]
When you mean “original cdr-tools”, do you mean the Debian fork (`wodim`/`genisoimage`), or do you mean the final version of Schily’s tools? I prefer working against the Debian fork because the license is a lot cleaner.

**Comment by Giulio-xyz** [comment]
I was referring to the fix/patch for Schily tools that you wrote you sent
Joerg and that unfortunately he coulnd't apply.

If it's not possible for you to publish the fix/patch for license reasons,
could you tell me whether the fix involved just the iso9660_date()
function, and if it's the same as the one for genisoimage or not?

Thanks!

**Comment by samboy** [comment]
*Edit* Let me be crystal clear here: I never gave Schilling a diff patch. Instead, I gave him a “if you replace this function with this code, it may fix the post-2027 issues with your code” email; scanning the Schilytools, I saw his code still had the post-2027 bug in it. I never compiled Schilling’s post-CDDL code (his code is quite hard to compile; it took me about a week to compile *just* `genisoimage`) much less made a formally tested patch.

Also, I do *not* support Schilling’s post-CDDL code, for the simple reason I prefer to not support code without clean licenses.

I agree with Debian here: The CDDL license does *not* mix with the GPL license, and despite the Debian branch not having some fixes and having issues being ignored for years, it has a clean license moving forward. I agree that Schilly’s next of kin will probably ever be aware of the issues, much less start legal action, and Eric Youngdale or whoever holds the rights to Yggdrasil’s code base will likewise never engage in legal action over the GPL vs. CDDL issue, but in open source it’s important we keep the license clean. If Schilling’s spouse/neice/whoever came forward and said “OK, we donate all of Schilling’s code to the public domain” or whatever, I would be singing a very different tune.

The fix in the Debian code base is this.  Take `iso9660_date()` and replace it with this new function, which does the same thing as Schilly’s old code, but without the bugs Schilly added:

```
int
iso9660_date(char *result, time_t crtime)
{
        struct tm       *local;
        struct tm       *gmt;
        int year, yday, hour, minute, second, zone;

        local = localtime(&crtime);
        result[0] = year = local->tm_year;
        result[1] = local->tm_mon + 1;
        result[2] = local->tm_mday;
        yday = local->tm_yday;
        result[3] = hour = local->tm_hour;
        result[4] = minute = local->tm_min;
        result[5] = second = local->tm_sec;

        /* Sam Trenholme's notes: The following code has been updated to be
         * Y2028 compliant.  That is *not* a typo: Year twenty-*twenty*eight
         * (**not 2038!**).
         * In other words, result[6] (the time zone) had invalid values for
         * files created on or after January 1, 2028.
         */

        /* First of all, the 9660 spec only allows timestamps between
         * January 1, 1900 and December 31, 2155.  So, handle timestamps
         * outside that spec by giving out timestamps at the end of the
         * spec.  It is unknown here in 2021 whether or not 2155 will
         * have a leap second; I will assume programmers are smart enough
         * to not have things crash if we have a leap second. */
        if(year < 0) {
                /* January 1, 1900 00:00:00 GMT */
                result[0] = 0;
                result[1] = 1;
                result[2] = 1;
                result[3] = 0;
                result[4] = 0;
                result[5] = 0;
                result[6] = 0; /* Time zone */
                return 0;
        } else if(year > 255) {
                /* December 31, 2155, 23:59:60 GMT */
                result[0] = 255;
                result[1] = 12;
                result[2] = 31;
                result[3] = 23;
                result[4] = 59;
                result[5] = 60;
                result[6] = 0; /* Time zone */
                return 0;
        }

        /* I have no idea why POSIX does not have tm_gmtoff.  Since it
         * doesn't, we have to calculate it ourselves. */
        gmt = gmtime(&crtime); /* Zaps local, be careful */

        zone = 0;

        /* We will never be more than one day off between GMT and local
         * time.  That in mind, if the year is different, we are one day
         * behind or ahead.  Otherwise, if the day is different, it will
         * always be a one day difference. */
        if(gmt->tm_year < year) {
                zone = 86400; /* 24 hours in seconds */
        } else if(gmt->tm_year > year) {
                zone = -86400;
        } else if(gmt->tm_yday < yday) {
                zone = 86400;
        } else if(gmt->tm_yday > yday) {
                zone = -86400;
        }

        /* Now that we account for different days, account for different
         * hours, minutes, and seconds. */
        zone += (hour - gmt->tm_hour) * 3600;
        zone += (minute - gmt->tm_min) * 60;
        zone += second - gmt->tm_sec;
        result[6] = zone / 900; /* Every 15 minutes in 9660 spec */

        return (0);
}
```

As stated above, I’m not interested in maintaining his CDDL + GPL code because of the licensing issues, nor in maintaining his pure-CDDL libraries.  When I contacted him, he did not run Ubuntu Linux or any other modern Linux distro (he was hardcore Solaris-only until the very end), so the use case for his code is not my use case.

I am *only* maintaining the pre-CDDL code for `genisoimage`. 

I’m closing this ticket as “UNSUPPORTED”. Perhaps you can become the maintainer for Schily’s code.

Thank you for your understanding.

**Comment by samboy** [comment]
Since I have had to put up a support boundary, I am locking the issue because I had an issue a with user who become irate when I put up support boundaries. This is not directed against you; this is just a policy I have with my own Git tickets to avoid an unpleasant exchange.

**Comment by samboy** [comment]
I think the best workaround here is to simply provide a Windows binary. Until I get a chance to do that, the workaround is:

* Install [Cygwin](https://cygwin.com) along with Git, GCC, and Make
* Check out this repo: `git clone https://github.com/samboy/img9660/`
* `cd src ; make`
* `cp img9660.exe /usr/bin/`

At this point, when in Cygwin, one can make images from the command line, e.g. `img9660 -J -V "CDName" -o image.iso DirectoryWithFiles/`
