### ISSUE TITLE
Please post your patches to our new repository

### ISSUE THREAD

**Issue by clausecker** [samboy/iso9660#3]
Hi there,

Heiko Eißfeldt has pointed me at your repository and the patches you wrote.  We recently started a repository to continue the development of Jörg's tools after his death, bundling the various existing efforts for patches.  It would be great if you could contribute your patches there:

    https://codeberg.org/schilytools/schilytools

**Comment by samboy** [comment]
I have left a comment there. My only question before proceeding is whether Ubuntu 20.04 LTS is an acceptable OS to develop and test the patch on.

**Comment by samboy** [comment]
As per my discussion there: I don’t think the “restore 8,192 wasted bytes” bug fix is a critical enough bug for patching schilytools, but the Y2028 issue is pretty critical.

**Comment by samboy** [comment]
As it turns out, after compiling and running `mkisofs` inside of Ubuntu 20.04, I verified that Schilling fixed the Y2028 bug when he was with us.

To verify the bug is fixed.

Here’s the test tarball: https://github.com/samboy/img9660/blob/master/test/geniso-Y2076-test.tar.xz

Extract this test tarball somewhere, say /tmp or whatever:

```
tar cvJf geniso-Y2076-test.tar.xz
```

`tar` will complain about future timestamps.  This is normal.

Now, in the directory where the tarball was extracted:

```
mkisofs -J -V "test" -o test.iso geniso-Y2076-test
```

Then let’s do a hexdump of that test.iso file:

```
hexdump -C test.iso  | less
```

Here is the relevant directory entries in my timezone (US/Pacific):

```
0000e050  00 00 00 00 00 00 79 06  15 05 03 33 e4 00 00 00  |......y....3....|
0000e060  01 00 00 01 07 32 30 32  31 2e 3b 31 28 00 ef ff  |.....2021.;1(...|
0000e070  ff ff ff ff ff ef 00 00  00 00 00 00 00 00 83 06  |................|
0000e080  15 05 04 0b e4 00 00 00  01 00 00 01 07 32 30 33  |.............203|
0000e090  31 2e 3b 31 28 00 ee ff  ff ff ff ff ff ee 00 00  |1.;1(...........|
0000e0a0  00 00 00 00 00 00 8d 06  15 05 04 1a e4 00 00 00  |................|
0000e0b0  01 00 00 01 07 32 30 34  31 2e 3b 31 28 00 ed ff  |.....2041.;1(...|
0000e0c0  ff ff ff ff ff ed 00 00  00 00 00 00 00 00 97 06  |................|
0000e0d0  15 05 04 2a e4 00 00 00  01 00 00 01 07 32 30 35  |...*.........205|
0000e0e0  31 2e 3b 31 28 00 ec ff  ff ff ff ff ff ec 00 00  |1.;1(...........|
0000e0f0  00 00 00 00 00 00 a1 06  15 05 04 36 e4 00 00 00  |...........6....|
0000e100  01 00 00 01 07 32 30 36  31 2e 3b 31 28 00 eb ff  |.....2061.;1(...|
0000e110  ff ff ff ff ff eb 00 00  00 00 00 00 00 00 b0 06  |................|
0000e120  15 05 05 03 e4 00 00 00  01 00 00 01 07 32 30 37  |.............207|
0000e130  36 2e 3b 31 00 00 00 00  00 00 00 00 00 00 00 00  |6.;1............|
```

The numbers to look for are `79 06 15 05 03 33 e4`, `83 06 15 05 04 0b e4`, `8d 06 15 05 04 1a e4`, `97 06 15 05 04 2a e4`, `a1 06 15 05 04 36 e4`, and `b0 06 15 05 05 03 e4`.

Those numbers will be different when `mkisofs` is run in different time zones, but they are in the form: YEAR 06 15 HOUR MINUTE SECOND TIMEZONE (could be `06 14` or `06 16` in your timezone).  Note here that TIMEZONE is *always* `e4`.  It will be a different number on your system, but the value will be the same for all of the files.

Let’s compare that output with the output from the buggy `genisoimage`:

```
0000e050  00 00 00 00 00 00 79 06  15 05 03 33 e4 00 00 00  |......y....3....|
0000e060  01 00 00 01 07 32 30 32  31 2e 3b 31 28 00 1e 00  |.....2021.;1(...|
0000e070  00 00 00 00 00 1e 00 00  00 00 00 00 00 00 83 06  |................|
0000e080  15 05 04 0b 84 00 00 00  01 00 00 01 07 32 30 33  |.............203|
0000e090  31 2e 3b 31 28 00 1e 00  00 00 00 00 00 1e 00 00  |1.;1(...........|
0000e0a0  00 00 00 00 00 00 8d 06  15 05 04 1a 84 00 00 00  |................|
0000e0b0  01 00 00 01 07 32 30 34  31 2e 3b 31 28 00 1e 00  |.....2041.;1(...|
0000e0c0  00 00 00 00 00 1e 00 00  00 00 00 00 00 00 97 06  |................|
0000e0d0  15 05 04 2a 84 00 00 00  01 00 00 01 07 32 30 35  |...*.........205|
0000e0e0  31 2e 3b 31 28 00 1e 00  00 00 00 00 00 1e 00 00  |1.;1(...........|
0000e0f0  00 00 00 00 00 00 a1 06  15 05 04 36 84 00 00 00  |...........6....|
0000e100  01 00 00 01 07 32 30 36  31 2e 3b 31 28 00 1e 00  |.....2061.;1(...|
0000e110  00 00 00 00 00 1e 00 00  00 00 00 00 00 00 b0 06  |................|
0000e120  15 05 05 03 84 00 00 00  01 00 00 01 07 32 30 37  |.............207|
0000e130  36 2e 3b 31 00 00 00 00  00 00 00 00 00 00 00 00  |6.;1............|
```

Here, the numbers are in different timezones: `79 06 15 05 03 33 e4` is correct, but all of the other timestamps have a different timezone: `83 06 15 05 04 0b 84`, `8d 06 15 05 04 1a 84`, `97 06 15 05 04 2a 84`, `a1 06 15 05 04 36 84`, and `b0 06 15 05 05 03 84`. 

We can see the bug is present because: 

* The timezone is different for post-Y2028 files
* The timezone (0x84) is -124, or 31 hours *before* GMT, an obviously invalid value (the lowest possible real-world value is -48, or 0xd0)

----

In terms of the “four wasted sectors” bug, I don’t feel comfortable fixing that bug in schilytools. I fix it in my fork of the code, because my use case is to fit as much data as I can on a 26,099 sector ISO image (53,450,752 bytes), so that extra 8192 bytes makes a difference. 

The fact this code was added indicates there was probably a good reason to have that code there. I would guess some obscure Ultrix/Irix/whatever CD-ROM driver had an issue if those sectors were not blank, so either Eric Youngdale or Schilling added that code so ISO images would work on those systems. Since the wasted bytes doesn’t really *break* anything, and since there *might* be users who still have systems which need those blank sectors out there, I wouldn’t change it. A code base this old has all kinds of little hack and fixes in it which resolve real-world issues.

People who want those extra 8,192 bytes can use `img9660` (this repo), or they can use `xorrisofs` (or Nero or whatever). People using `mkisofs` are using tried and true code.

**Comment by samboy** [comment]
Closing: Nothing worth fixing in schilytools.
